Controllers/ReportsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NotificationsSystem.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NotificationsSystem.Controllers
{
    [Authorize(AuthenticationSchemes = "Application")]
    public class ReportsController : BaseController
    {
        public ReportsController(IUserRepository userRepository)
            : base(userRepository)
        {
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                return View("Index", this.GetAllSheets());
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("ErrorPage");
            }
            
        }

        [HttpPost]
        public IActionResult TasksList(string filter = null)
        {
            try
            {
                ViewBag.Filter = filter;
                return View(this.GetAllTasks(filter));
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("ErrorPage");
            }
        }

        [HttpPost]
        public IActionResult Task(string range, IList<string> row)
        {
            try
            {
                var task = (IList<object>)row.Cast<object>().ToList();
                this.AddTask(range, new List<IList<object>>() { task });
                return Ok();
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("ErrorPage");
            }
        }       
    }
}

Views/Shared/ErrorPage.cshtml
@{ 
    ViewBag.Title = "Error Page";
}
<h1 class="text-center mt-3">Error!</h1>
<h3 class="text-center">@ViewBag.ErrorMessage</h3>

Views/Shared/Spinner.cshtml
<link type="text/css" href="~/css/spinner.css" rel="stylesheet" asp-append-version="true">
<div class="d-flex justify-content-center">
    <div class="lds-css ng-scope">
        <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <partial name="_ThemeStyles" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
            <a href="@Url.Action("Index", "Home")" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">Home</a>
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class=" nav-link " href="@Url.Action("Index","Managers")">
                            <p class="font-weight-bold">Managers</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class=" nav-link " href="@Url.Action("Index","Reports")">
                            <p class="font-weight-bold">Reports</p>
                        </a>
                    </li>
                </ul>
                <hr class="my-3">
                <ul class="navbar-nav mb-md-3">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Settings")">
                            <p class="font-weight-bold">Settings</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("GoogleLogout","Account")">
                            <p class="font-weight-bold">Log Out</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="main-content">
        @RenderBody()
    </div>
    <partial name="_ThemeScripts" />
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_ThemeScripts.cshtml
<!-- Argon Scripts -->
<!-- Core -->
<script src="~/vendor/jquery/dist/jquery.min.js" asp-append-version="true"></script>
<script src="~/vendor/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
<!-- Docs JS -->
<script src="~/vendor/anchor-js/anchor.min.js" asp-append-version="true"></script>
<script src="~/vendor/clipboard/dist/clipboard.min.js" asp-append-version="true"></script>
<script src="~/vendor/holderjs/holder.min.js" asp-append-version="true"></script>
<script src="~/vendor/prismjs/prism.js" asp-append-version="true"></script>
<!-- Optional JS -->
<script src="~/vendor/chart.js/dist/Chart.min.js" asp-append-version="true"></script>
<script src="~/vendor/chart.js/dist/Chart.extension.js" asp-append-version="true"></script>
<script src="~/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" asp-append-version="true"></script>
<!-- Argon JS -->
<script src="~/js/argon.min.js" asp-append-version="true"></script>

Views/Shared/_ThemeStyles.cshtml
<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<!-- Icons -->
<link href="~/vendor/nucleo/css/nucleo.css" rel="stylesheet" asp-append-version="true">
<link href="~/vendor/@@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet" asp-append-version="true">
<!-- Argon CSS -->
<link type="text/css" href="~/css/argon.min.css" rel="stylesheet" asp-append-version="true">